Update to upstream 1.13.0
unikraft/lib-googletest pull request #2
Opened 2023-05-11 13:19 UTC by andreittr

### Description of changes

Update Google Test to upstream 1.13.0, as well as clean up build scripts & documentation.

2023-08-06 15:01 UTC, mariasfiraiala requested changes
The changes look good, thanks @andreittr. Regarding the documentation part, however, the README specifies the order of the libraries  which we don't use anymore (and has `newlib` mentioned as well - kinda obsolete).

AFAIK, the latest correct order is

```Makefile
LIBS := $(UK_LIBS)/lib-libcxxabi:$(UK_LIBS)/lib-libcxx:$(UK_LIBS)/lib-compiler-rt:$(UK_LIBS)/lib-libunwind:$(UK_LIBS)/lib-musl:$(UK_LIBS)/lib-googletest
```

Do you mind changing that too @andreittr? Actually the whole README should be updated to have the md format. I can add a commit to achieve that, if you find it too cumbersome.

2023-08-07 10:58 UTC, andreittr commented
> The changes look good, thanks @andreittr. Regarding the documentation part, however, the README specifies the order of the libraries which we don't use anymore (and has `newlib` mentioned as well - kinda obsolete).
> 
> AFAIK, the latest correct order is
> 
> ```makefile
> LIBS := $(UK_LIBS)/lib-libcxxabi:$(UK_LIBS)/lib-libcxx:$(UK_LIBS)/lib-compiler-rt:$(UK_LIBS)/lib-libunwind:$(UK_LIBS)/lib-musl:$(UK_LIBS)/lib-googletest
> ```
> 
> Do you mind changing that too @andreittr? Actually the whole README should be updated to have the md format. I can add a commit to achieve that, if you find it too cumbersome.

Good point @mariasfiraiala , thanks! I'll add a commit updating the README to be roughly in line with ones in more up-to-date libs. I'll also simplify the lib order paragraph to just "put at the end of the lib list".

2023-08-07 19:57 UTC, mariasfiraiala requested changes
Thanks @andreittr, 2 last comments from me below. After this, I think we should merge this.

2023-08-07 19:57 UTC, mariasfiraiala commented on README.md
> +Being a C++ library, libcxx is required.
```suggestion
Being a C++ library, `libcxx` is required.
```

2023-08-07 19:57 UTC, mariasfiraiala commented on README.md
> +This library should come at the end of the dependency list.
```suggestion
`lib-googletest` should come at the end of the dependency list.
```

It isn't clear enough what library should come last.

2023-08-07 20:24 UTC, mariasfiraiala approved these changes
All good now, thanks a lot for the effort, @andreittr!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-08-11 12:11 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-11 12:21 UTC, closed without merging